### ISSUE TITLE
Why don't we use UCX_TLS=all

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#245] opened 2019-10-12 00:15 UTC
Hypothetically we should be able to set `UCX_TLS=all` and UCX should choose all available transports.  However in practice we don't do this, we set a specific set manually.  I believe that this came out of need, simply setting `all` wasn't giving us the performance that we expected.  It would be useful to start exploring why this is, and see if we can identify issues upstream that would help to address this long-term.

cc @pentschev @Akshay-Venkatesh

**Comment by pentschev** [comment] 2019-10-14 08:45
I agree, this would be the simplest. IMO more important than `UCX_TLS`, if we didn't need to set the `UCX_NET_DEVICES` variable, things would then be much easier, given that may change depending on system's topology.

**Comment by MattBBaker** [comment] 2019-10-15 19:08
I can't speak to the earliest days of ucx-py, but I believe part of the motivation was that the TCP TL wasn't working well, so the UCX_TLS was being manually set to work around early TCP UCX bugs. All of that should be fixed now. I'm not sure if UCX_NET_DEVICES is needed either. In previous UCX apps I've never needed to manually set that env variable either. 

What happens if none of the variables are set on the latest release?

**Comment by jakirkham** [comment] 2019-10-15 19:26
What about `UCX_SOCKADDR_TLS_PRIORITY` or `UCXPY_IFNAME`? Are these still needed? Or can we dispose of them as well?

**Comment by MattBBaker** [comment] 2019-10-15 20:03
`UCX_SOCKADDR_TLS_PRIORITY` Likely isn't, but I'm not sure how `UCXPY_IFNAME` is meant to be used.

**Comment by quasiben** [comment] 2019-10-15 20:05
`UCXPY_IFNAME` is an internal env var specific to ucx-py mostly used for our testing CI

**Comment by jakirkham** [comment] 2019-10-15 20:17
Well thus far I've been unable to run our test suite when setting `UCX_TLS="all"`. Instead it hangs when trying to run the tests in `tests/test_multiple_nodes.py` (none of which complete). This is identical to the behavior I see when leaving `UCX_TLS` unset (guessing that is the same as setting it to `"all"`). Have been using commit ( https://github.com/rapidsai/ucx-py/commit/c3e7a457c1f7990536af07f7a3f917aadd55e082 ) to test.

**Comment by jakirkham** [comment] 2019-10-17 16:09
@quasiben made a good point earlier that the hang could be the same as the one in issue ( https://github.com/rapidsai/ucx-py/issues/250 ) or at least caused by a lack of signal handling in ucx-py. Some thoughts on how to handle this in [this comment on signal handling]( https://github.com/rapidsai/ucx-py/issues/250#issuecomment-542394529 ). Though it's worth noting that identifying the signal sent will only be the first step in debugging the underlying issue.

**Comment by MattBBaker** [comment] 2019-10-17 17:20
I've not been able to test this yet, (Our DGXs are in high demand). Looking through the test code, I suspect the test_multiple_nodes.py test may end up in a path where it blocks on an await and no one is calling `ucp.progress()`.  I have some (very WIP) code [here](https://github.com/MattBBaker/ucx-py/blob/topic/ucp_address/tests/test_send_recv_no_listener.py#L26) for a test that ensures that some task is always calling `ucp.progress()` I'm not sure if this is the right or best way to do this, but wanted to throw it out there in case the `tests/test_multiple_nodes.py` test was under progressed.

**Comment by pentschev** [comment] 2021-08-13 21:11
To provide an update, this is almost possible. The primary reason we still have to specify `UCX_TLS` today is to [create a CUDA context _before_ initializing UCX](https://github.com/dask/distributed/blob/17cd4db5a86d8d78b6a4ac15a6fa41ad4e609ff6/distributed/comm/ucx.py#L52-L63) to ensure CUDA<->IB device mapping is done properly. A feature to prevent that requirement is planned for UCX 1.12, when that lands we're probably able to use `UCX_TLS=all` for all cases.

**Comment by jakirkham** [comment] 2021-11-19 20:34
IIUC PR ( https://github.com/rapidsai/dask-cuda/pull/792 ) & PR ( https://github.com/dask/distributed/pull/5526 ) should resolve this

Though please feel free to correct me Peter :)

**Comment by pentschev** [comment] 2021-11-19 20:41
It should fix/improve the issue in Dask, yes. However, the last remaining issue I mentioned in https://github.com/rapidsai/ucx-py/issues/245#issuecomment-898722549 still stands, therefore I think we should keep this open for now.

**Comment by quasiben** [comment] 2023-03-27 19:23
We now recommend using `all`

**Closed by quasiben** 2023-03-27 19:23 UTC
