### ISSUE TITLE
Running Benchmark on DGX2 fails

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#336] opened 2019-11-21 21:10 UTC
I was recently granted access to a DGX2 and ran the new benchmark @madsbk recently added and got a new error (yay!)

> ucp.exceptions.UCXError: User-defined limit was reached

Full traceback below:

```
(cudf_dev101) bzaitlen@exp02:/datasets/bzaitlen/GitRepos/ucx-py$ python benchmarks/local-send-recv.py -o cupy  -n "100MB" --server-dev 1 --client-dev 2 --reuse-alloc --server-address 172.22.1.27
[1574370360.485816] [exp02:63952:0]    ucp_context.c:1004 UCX  ERROR exceeded transports/devices limit (71 requested, up to 64 are supported)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/datasets/bzaitlen/miniconda3/envs/cudf_dev101/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/datasets/bzaitlen/miniconda3/envs/cudf_dev101/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/datasets/bzaitlen/GitRepos/ucx-py/benchmarks/local-send-recv.py", line 18, in server
    ucp.init()
  File "/datasets/bzaitlen/GitRepos/ucx-py/ucp/public_api.py", line 74, in init
    options, blocking_progress_mode=blocking_progress_mode
  File "ucp/_libs/core.pyx", line 358, in ucp._libs.core.ApplicationContext.__cinit__
    assert_ucs_status(status)
  File "ucp/_libs/core.pyx", line 30, in ucp._libs.core.assert_ucs_status
    raise UCXError(msg)
ucp.exceptions.UCXError: User-defined limit was reached
```

**Comment by quasiben** [comment] 2019-11-21 22:49
I'm not sure what we should do here -- I think this may be a UCX core issue.  It seems like UCX enumerates all the various transport methods and currently has a [max of 64](https://github.com/openucx/ucx/blob/9139170278a6c38997112c8447aa93c40ac24ccf/src/ucp/core/ucp_types.h#L21

With `TRACE` logging turned on you can see all the TLS methods listed out:

```
...
[1574376130.309445] [exp02:17327:0]    ucp_context.c:590  UCX  TRACE allowed transport 0 : 'all'
[1574376130.309448] [exp02:17327:0]    ucp_context.c:377  UCX  TRACE enabling tl 'all'
[1574376130.309449] [exp02:17327:0]    ucp_context.c:504  UCX  TRACE tcp/docker0 is enabled
[1574376130.309451] [exp02:17327:0]    ucp_context.c:377  UCX  TRACE enabling tl 'all'
[1574376130.309452] [exp02:17327:0]    ucp_context.c:504  UCX  TRACE tcp/ib7 is enabled
[1574376130.309454] [exp02:17327:0]    ucp_context.c:377  UCX  TRACE enabling tl 'all'
[1574376130.309455] [exp02:17327:0]    ucp_context.c:504  UCX  TRACE tcp/ib5 is enabled
[1574376130.309457] [exp02:17327:0]    ucp_context.c:377  UCX  TRACE enabling tl 'all'
[1574376130.309458] [exp02:17327:0]    ucp_context.c:504  UCX  TRACE tcp/ib3 is enabled
[1574376130.309460] [exp02:17327:0]    ucp_context.c:377  UCX  TRACE enabling tl 'all'
...
```

**Comment by quasiben** [comment] 2019-11-21 22:50
@Akshay-Venkatesh have you used UCX on a DGX2 ?

**Comment by madsbk** [comment] 2019-11-22 08:36
A workaround is to set the TLS manually: `UCX_TLS=tcp,cuda_copy,cuda_ipc,sockcm`.

103.25 GB/s isn't bad :)

```
$ UCX_TLS=tcp,cuda_copy,cuda_ipc,sockcm UCXPY_IFNAME=enp134s0f1  python local-send-recv.py  -n "100MB" --server-dev 1 --client-dev 2--object_type=cupy --reuse-alloc

Roundtrip benchmark
--------------------------
n_iter      | 10
n_bytes     | 100.00 MB
object      | cupy
reuse alloc | True
==========================
Device(s)   | 1, 2
Average     | 73.70 GB/s
--------------------------
Iterations
--------------------------
000         | 21.67 GB/s
001         | 84.72 GB/s
002         |103.25 GB/s
003         |106.59 GB/s
004         |102.35 GB/s
005         | 99.21 GB/s
006         |106.53 GB/s
007         | 99.80 GB/s
008         |104.03 GB/s
009         |102.18 GB/s
```

**Comment by pentschev** [comment] 2019-11-25 10:07
I think this is because of the topology of InfiniBand interfaces. On the DGX1 we can just use one IB for each GPU pair in increasing order. On the DGX2 that doesn't hold anymore, `mlx5_4:1` and `mlx5_5:1` aren't connected to any GPUs via a single switch, the connections that we should be using are then `mlx5_0:1`-`mlx5_3:1` for GPUs `0-7` and `mlx5_6:1`-`mlx5_9:1` for GPUs `8-15`. That assumption may be the cause for this issue.

**Comment by quasiben** [comment] 2019-11-26 19:48
cc @MattBBaker

**Comment by MattBBaker** [comment] 2019-11-26 20:03
This is definitely a core UCX issue. I'll file an issue, something along the lines of, "DGX-2 system exceeds build in 64 transport limit"

**Comment by MattBBaker** [comment] 2019-11-26 20:04
On a side note, I'm definitely seeing Summit report 4 total IB cards, and only 1 configured. I'll run down Ops people after the holidays to see if there an an alloc option or if MPI is doing some magic with them.

**Comment by quasiben** [comment] 2019-11-26 21:54
Thanks @MattBBaker!

**Comment by pentschev** [comment] 2019-11-26 23:25
> On a side note, I'm definitely seeing Summit report 4 total IB cards, and only 1 configured. I'll run down Ops people after the holidays to see if there an an alloc option or if MPI is doing some magic with them.

Yeah, that will definitely help performance along the way with multi-GPU. :)

**Comment by jakirkham** [comment] 2020-01-15 04:21
@MattBBaker, am curious did you file this issue already?

**Comment by quasiben** [comment] 2020-01-15 06:09
I filed an issue here: https://github.com/openucx/ucx/issues/4557

**Comment by MattBBaker** [comment] 2020-01-15 14:50
@quasiben filed it. We should ping the UCX call next week to bring it up. I know ORNL got in some DGX2s and I'll see about getting time on those to replicate.

**Comment by jakirkham** [comment] 2020-01-15 19:23
Thanks @quasiben!

That would be great @MattBBaker. Would be interested to know if you are able to reproduce 🙂

**Comment by pentschev** [comment] 2020-05-29 23:13
Currently we need to set `UCX_TLS` manually and that works in a DGX-2. The IB issue has been resolved by https://github.com/openucx/ucx/pull/4905 .

**Comment by pentschev** [comment] 2021-08-18 19:19
The issue here doesn't occur anymore with UCX 1.11:

```
$ python benchmarks/send-recv.py -o cupy  -n "100MB" --server-dev 1 --client-dev 2 --reuse-alloc
Server Running at 10.33.228.80:34024
Client connecting to server at 10.33.228.80:34024
Roundtrip benchmark
--------------------------
n_iter          | 10
n_bytes         | 95.37 MiB
object          | cupy
reuse alloc     | True
transfer API    | TAG
UCX_TLS         | all
UCX_NET_DEVICES | all
==========================
Device(s)       | 1, 2
Average         | 34.95 GiB/s
Median          | 89.54 GiB/s
--------------------------
Iterations
--------------------------
000         | 5.40 GiB/s
001         |81.78 GiB/s
002         |88.06 GiB/s
003         |86.26 GiB/s
004         |89.73 GiB/s
005         |89.35 GiB/s
006         |91.52 GiB/s
007         |94.97 GiB/s
008         |90.95 GiB/s
009         |92.04 GiB/s
```

Closing.

**Closed by pentschev** 2021-08-18 19:19 UTC
