### ISSUE TITLE
Run benchmarks in CI

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucx-py#265] opened 2019-10-15 23:36 UTC
There is a [`benchmarks` directory in this repo]( https://github.com/rapidsai/ucx-py/tree/c3e7a457c1f7990536af07f7a3f917aadd55e082/benchmarks ), which contains a variety of scripts. To make sure these don't bit rot (and possibly update them), it would be useful to start running them as part of CI. Considering as we know what machine CI is running on, we may want to record and share the results from running the benchmarks in the logs.

**Comment by quasiben** [comment] 2019-10-16 02:06
for many of the benchmarks we will need a CI machine with two GPUs.  I have a PR in to resolve one benchmark file: https://github.com/rapidsai/ucx-py/pull/254

I suspect other files can either be reworked or removed

**Comment by jakirkham** [comment] 2019-10-16 20:12
Sounds good.

IIRC @pentschev created some useful tooling for benchmarking while measuring performance of CuPy. Maybe we can leverage that here too?

**Comment by pentschev** [comment] 2020-05-29 22:58
Just for a brief update: I've recently been working on this, I have some scripts to run on our DGXs, but I'm still cleaning up several tests that fail under different conditions, meaning we still have issues that can be reproduced in such tests and benchmarks.

**Comment by pentschev** [comment] 2021-08-13 21:16
This is now done separately on a DGX-1, given CI doesn't have NVLink/IB capabilities. Results in https://github.com/pentschev/ucx-py-ci/tree/test-results . I'm gonna go ahead and close this, since it's unlikely we'll have a different solution any time soon.

**Closed by pentschev** 2021-08-13 21:16 UTC
