### ISSUE TITLE
Join benchmark causes fatal error

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/ucx-py#339] opened 2019-11-26 20:33 UTC
When running this example code (additional discussion in https://github.com/rapidsai/ucx-py/pull/333 )

<details>

```python
import asyncio
import time
from time import perf_counter as clock

import dask
import dask.array as da
import dask.dataframe as dd
from dask_cuda import DGX
from dask_cuda.initialize import initialize
from distributed import Client, wait
from distributed.utils import format_bytes

import cupy
import cudf
import dask_cudf
import pytest

enable_tcp_over_ucx = True
enable_infiniband = True
enable_nvlink = True

initialize(
    create_cuda_context=True,
    enable_tcp_over_ucx=enable_tcp_over_ucx,
    enable_infiniband=enable_infiniband,
    enable_nvlink=enable_nvlink,
)

cluster = DGX(
    interface="enp1s0f0",
    protocol="ucx",
    enable_tcp_over_ucx=enable_tcp_over_ucx,
    enable_infiniband=enable_infiniband,
    enable_nvlink=enable_nvlink,
    silence_logs=False,
    dashboard_address=":8789"
)

client = Client(cluster)
client

n_rows = 100_000_000
n_partitions = 100
n_keys = 100_000_000

def make_partition(n_rows, n_keys, name):
    return cudf.DataFrame({
        name: cupy.random.random(n_rows),
        "id": cupy.random.randint(0, n_keys, size=n_rows),
    })

left = dd.from_delayed(
    [dask.delayed(make_partition)(n_rows // n_partitions, n_keys, "x") for _ in range(n_partitions)],
    meta=make_partition(1, n_keys, "x")
)
right = dd.from_delayed(
    [dask.delayed(make_partition)(n_rows // n_partitions, n_keys, "y") for _ in range(n_partitions)],
    meta=make_partition(1, n_keys, "y")
)

left, right = dask.persist(left, right)


out = left.merge(right, on=["id"])
out = out.persist()
_ = wait(out)
```

</details>

I get the following error

```
mlx5: dgx15: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
0000000c 00000000 00000000 00000000
00000000 93005204 080001d4 00213ad2
[dgx15:76056:0:76056] rc_verbs_iface.c:69   send completion with error: local protection error qpn 0x1d4 wrid 0x2 vendor_err 0x52
==== backtrace ====
    0  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/lib/python3.7/site-packages/ucp/_libs/../../../../libucs.so.0(ucs_fatal_error_message+0x51) [0x7f9cf9a47121]
    1  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/lib/python3.7/site-packages/ucp/_libs/../../../../libucs.so.0(+0x22ee7) [0x7f9cf9a4aee7]
    2  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/lib/python3.7/site-packages/ucp/_libs/../../../../libucs.so.0(ucs_log_dispatch+0xd9) [0x7f9cf9a4b019]
    3  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/lib/python3.7/site-packages/ucp/_libs/../../../../ucx/libuct_ib.so.0(+0x1b46e) [0x7f9cf674b46e]
    4  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/lib/python3.7/site-packages/ucp/_libs/../../../../ucx/libuct_ib.so.0(+0x1baae) [0x7f9cf674baae]
    5  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/lib/python3.7/site-packages/ucp/_libs/../../../../libucp.so.0(ucp_worker_progress+0x6a) [0x7f9cf9a937ba]
    6  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/lib/python3.7/site-packages/ucp/_libs/core.cpython-37m-x86_64-linux-gnu.so(+0x13ad2) [0x7f9cf9afead2]
    7  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/lib/python3.7/site-packages/ucp/_libs/core.cpython-37m-x86_64-linux-gnu.so(+0x2c7ff) [0x7f9cf9b177ff]
    8  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyObject_FastCallKeywords+0x3fb) [0x55fde0ed516b]
    9  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(+0x204da3) [0x55fde0f68da3]
```

</details>

<details>
<summary>rest of traceback </summary>

```
   10  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyMethodDef_RawFastCallDict+0x199) [0x55fde0e9ccd9]
   11  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyCFunction_FastCallDict+0x21) [0x55fde0e9cf01]
   12  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x5c64) [0x55fde0f3ad54]
   13  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55fde0ecbcfb]
   14  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x6f0) [0x55fde0f357e0]
   15  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55fde0ecbcfb]
   16  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x6f0) [0x55fde0f357e0]
   17  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55fde0ecbcfb]
   18  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x6f0) [0x55fde0f357e0]
   19  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55fde0ecbcfb]
   20  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x6f0) [0x55fde0f357e0]
   21  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalCodeWithName+0xba9) [0x55fde0e7b1d9]
   22  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallKeywords+0x387) [0x55fde0ecbf87]
   23  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x6f0) [0x55fde0f357e0]
   24  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalCodeWithName+0xba9) [0x55fde0e7b1d9]
   25  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallDict+0x400) [0x55fde0e7bc20]
   26  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyObject_Call_Prepend+0x63) [0x55fde0e9ae23]
   27  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(PyObject_Call+0x6e) [0x55fde0e8d51e]
   28  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x1f4c) [0x55fde0f3703c]
   29  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallDict+0x10b) [0x55fde0e7b92b]
   30  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyObject_Call_Prepend+0xde) [0x55fde0e9ae9e]
   31  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(PyObject_Call+0x6e) [0x55fde0e8d51e]
   32  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x1f4c) [0x55fde0f3703c]
   33  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55fde0ecbcfb]
   34  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x6f0) [0x55fde0f357e0]
   35  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55fde0ecbcfb]
   36  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x6f0) [0x55fde0f357e0]
   37  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallKeywords+0xfb) [0x55fde0ecbcfb]
   38  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x416) [0x55fde0f35506]
   39  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalCodeWithName+0x2f9) [0x55fde0e7a929]
   40  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyFunction_FastCallKeywords+0x387) [0x55fde0ecbf87]
   41  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalFrameDefault+0x14dc) [0x55fde0f365cc]
   42  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_PyEval_EvalCodeWithName+0x2f9) [0x55fde0e7a929]
   43  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(PyEval_EvalCodeEx+0x44) [0x55fde0e7b7e4]
   44  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(PyEval_EvalCode+0x1c) [0x55fde0e7b80c]
   45  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(+0x22fac4) [0x55fde0f93ac4]
   46  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(PyRun_StringFlags+0x7d) [0x55fde0f9ed0d]
   47  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(PyRun_SimpleStringFlags+0x3f) [0x55fde0f9ed6f]
   48  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(+0x23ae6d) [0x55fde0f9ee6d]
   49  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(_Py_UnixMain+0x3c) [0x55fde0f9f1dc]
   50  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f9cfbf06b97]
   51  /home/nfs/mrocklin/miniconda/envs/ucx-benchmark/bin/python(+0x1e0d3d) [0x55fde0f44d3d]
```

</details>

cc @madsbk @pentschev @MattBBaker

**Comment by mrocklin** [comment] 2019-11-26 20:35
This error goes away if I set

```python
enable_infiniband = False
```

**Comment by pentschev** [comment] 2019-11-29 23:23
When you say that the error goes away, does that mean the task actually completes successfully? For me it always crashes with UCX, no matter what combination (NVLink+IB, NVLink alone, IB alone, TCP over UCX).

**Comment by mrocklin** [comment] 2019-11-30 00:05
Yes, the task was completing successfully for me

**Comment by jakirkham** [comment] 2020-01-15 04:39
I tried running this recently in the hopes of debugging it and it hung the box. 😞

**Comment by pentschev** [comment] 2020-05-29 23:23
We have solved many issues with IB and UCX in general in the past few months. Interestingly, this still fails, I'll have to follow up on this issue.

**Comment by pentschev** [comment] 2021-04-23 14:00
I haven't seen this issue for quite a while, more specifically since we stopped building UCX packages with MOFED support (because MOFED 4.x doesn't provide any compatibility between versions). I think it's safe to assume that that was the cause, or the issue has been resolved upstream in UCX. I'm closing for now.

**Closed by pentschev** 2021-04-23 14:00 UTC
