### ISSUE TITLE
How to acclerate stream_recv on client, should I use EndpointReuse?

### ISSUE THREAD

**Issue by sunkenQ** [rapidsai/ucx-py#1030] opened 2024-03-08 09:04 UTC
In my code, I started two listener to receive torch.tensor and np.ndarray using asyncio.gather，and use client to send a 6000x15000 torch.tensor on cuda and then immediately send a 6000x5 np.ndarray to server, I found that `await comm.stream_recv(endpoint, peer_info_arr, peer_info_arr.nbytes)`cost a lot of time. 
For this problem, I find class EndpointReuse in ucp source code, it seems can solve my problem, but I don't know how to use EndpointReuse, especially whether to close it. Should I use EndpointReuse, or is there another better way?

EndpointReuse Server Code:
```
import asyncio
import ucp
import numpy as np
from ucp.endpoint_reuse import EndpointReuse, EPHandle


host = ucp.get_address()
port = 15000
data = np.zeros(shape=(10, 10), dtype=np.float32)


async def recv_data(ep: EndpointReuse):
    print(EndpointReuse.existing_endpoints.items(), ep)
    await ep.recv(data)
    # close will destory endpoint.handle
    # ep.close()

async def main():
    global lf
    lf = EndpointReuse.create_listener(recv_data, port)
    
    print(f"Server is listening on {host}:{port}")

    while not lf.closed():
        await asyncio.sleep(0.1)

if __name__ == '__main__':
    asyncio.run(main())
```

EndpointReuse Client Code:
```
import asyncio
import numpy as np
from ucp.endpoint_reuse import EndpointReuse
import time

port = 15000
arr = np.random.randn(10, 10).astype(np.float32)
reuse_endpoint = EndpointReuse
host = "x.x.x.x"

async def main(ep: EndpointReuse):
    # send message
    await ep.send(arr)  # send the real message
    # I tried close the endpoint, abort and just return, but doesn't work
    # ep.close()


if __name__ == '__main__':
    ep = asyncio.run(reuse_endpoint.create_endpoint(host, port))

    for _ in range(10):
        start = time.perf_counter()
        asyncio.run(main(ep))
        end = time.perf_counter()
        print(f"Time taken: {(end - start) * 1000:.4f} ms")
        time.sleep(0.5)
```

![image](https://github.com/rapidsai/ucx-py/assets/41413441/88c4a5b5-a665-470e-8187-e4653416e3b8)

**Comment by pentschev** [comment] 2024-03-08 14:04
The cost you refer to is establishing connections, this is indeed expensive, even more so depending on the transports that are available between the two processes.

From what I can see in the code you posted the problem is you're creating new endpoints every time you attempt to transfer a new message, is that intentional? Between two processes what you can do is store the listener's endpoint you get from the callback for later reuse, in that case you'd only create the endpoint once on each process and reuse them, which is essentially what `EndpointReuse` does. What I'm suggesting is something similar to the following:

<details><summary>server.py</summary>

```python
listener_eps = []
async def listener_cb(ep):
    listener_eps.append(ep)

listener = ucp.create_listener(listener_cb)

while len(listener_eps) == 0:
    await asyncio.sleep(0)

for ep in listener_eps:
    # Here transfer data back and forth with the client
    await ep.send(...)
    await ep.recv(...)
```
</details>

<details><summary>client.py</summary>

```python
ep = await ucp.create_endpoint(listener_address, listener_port)

# Here transfer data back and forth with the server
await ep.send(...)
await ep.recv(...)
```

</details>

Would something like the above work for you?

You can use `EndpointReuse` but note that this is deprecated and will not be ported over to [UCXX](https://github.com/rapidsai/ucxx) when the UCX-Py repository gets archived, it was formerly introduced to resolve some issues with NVLink we had in the past and was only used in [Distributed](https://github.com/dask/distributed/pull/3953) but it is not used there anymore either.

**Comment by sunkenQ** [comment] 2024-03-08 16:46
@pentschev Thank you for your quick reply! 

> From what I can see in the code you posted the problem is you're creating new endpoints every time you attempt to transfer a new message, is that intentional?

I actually don't want the client to recreate the Endpoint every time, I just following the code at the link. [Send/Recv NumPy Arrays](https://ucx-py.readthedocs.io/en/latest/quickstart.html#process-1-server)

I want server use `create_listener` to create 2 ports and listen continuously, using 6000x15000 torch.tensor(cuda) and 6000x5 np.ndarray as buffers to receive data from the client. and each client only needs create_endpoint for the first transfer, after which it only needs to reuse ep.  I don't quite understand your code, it's very different from the example in the link, can you provide a runnable code that client can reuse the endpoint to continuously transfer np.ndarray or any other data to the server?  Thank you very much for your help!

To illustrate my confusion, I can't understand the following code how this listener can keep waiting for the client's request?
And if I don't use ep.close how do I know if the client's request to the server port has completed? Or is ep.close only needed to completely terminate a client?

> server.py
> ```python
> listener_eps = []
> async def listener_cb(ep):
>     listener_eps.append(ep)
> 
> listener = ucp.create_listener(listener_cb)
> 
> while len(listener_eps) == 0:
>     await asyncio.sleep(0)
> 
> for ep in listener_eps:
>     # Here transfer data back and forth with the client
>     await ep.send(...)
>     await ep.recv(...)
> ```

**Comment by pentschev** [comment] 2024-03-08 22:31
It's not very different from the example in the link, the only thing primarily different is the fact that the listener callback is just doing one task: pushing the endpoint to a client into a list. Each of the endpoints in that list is an endpoint to a client, therefore as long as you keep the reference to the endpoint on both ends and do not call `ep.close()`/`ep.abort()` on either the client or the server, you can keep on reusing the same endpoint pair forever. In your server code you have this callback:

```python
async def recv_data(ep: EndpointReuse):
    print(EndpointReuse.existing_endpoints.items(), ep)
    await ep.recv(data)
    # close will destory endpoint.handle
    # ep.close()
```

As you noticed yourself, once the callback goes out of scope (or `ep.close()` is called), the endpoint will be closed/destroyed. This is exactly what you're trying to prevent. Therefore, what I suggested is that you don't do anything in the callback except for pushing that endpoint to a `listener_eps` list, thus the endpoint will outlive the callback and you can still use it in your `main()` function, at that point you can simply write `ep = listener_eps[0]` (assuming you expect a single client to connect) and operate on the endpoint in the same way as you operate in your in client. Once again, the key is to only make sure you keep the endpoint reference alive on both ends and you're essentially reusing the endpoint.


> And if I don't use ep.close how do I know if the client's request to the server port has completed?

That's what `await` is for, until you `await` a send/recv coroutine you don't know if it has completed.

> Or is ep.close only needed to completely terminate a client?

Yes, `ep.close()` should only be used to close a connection and may be used by either server or client process, after which point you can't anymore trigger any send operations, but may still be able to receive messages that are in transit. You can use `ep.closed()` to verify the endpoint was closed on either end, and to prevent missing any received messages (`ep.closed()` may evaluate to `True` while there are still receive messages in transit) you can keep on calling [`ep.recv()` to consume all messages, until a `UCXCloseError` is raised](https://github.com/rapidsai/ucx-py/blob/50532d099d564659a8f98043a0164ed49cd30f95/ucp/core.py#L719-L722).

**Comment by sunkenQ** [comment] 2024-03-09 06:17
> It's not very different from the example in the link, the only thing primarily different is the fact that the listener callback is just doing one task: pushing the endpoint to a client into a list. Each of the endpoints in that list is an endpoint to a client, therefore as long as you keep the reference to the endpoint on both ends and do not call `ep.close()`/`ep.abort()` on either the client or the server, you can keep on reusing the same endpoint pair forever. In your server code you have this callback:

I previously thought that the callback function set in server create_listener can only receive/send data and then process the data, so all my functions were written in the callback function, and make `main()` code just to keep listener alive like the example code. 
```
async def main():
    global lf
    lf = ucp.create_listener(send, port)

    while not lf.closed():
        await asyncio.sleep(0.1)
```

Now I understand that the listener can only be used to create the ep and keep it for a long time, the rest of the functionality can be implemented in the main() function.So I modified the code, but the client could not finish create_endpoint, but kept getting stuck. where is the bug in my code? Sincerely appreciate your help！

**Server**
```
import ucp
import asyncio
import numpy as np
from ucp import Endpoint
from typing import List

buffer = np.random.randn(10, 10).astype(np.float32)
listener_eps: List[Endpoint] = []

async def listener_cb(ep: Endpoint):
    global listener_eps
    # wait client's ep, and append ep to list
    listener_eps.append(ep)

listener = ucp.create_listener(listener_cb, port=15000)

async def main():
    global listener_eps
    while len(listener_eps) == 0:
        print(listener_eps)
        await asyncio.sleep(0.1)

    # use exist ep to recv data, do not use close() to destory ep
    # I have 4 client connect to server, so I use for loop to recv
    for ep in listener_eps:
        await ep.recv(buffer)

    # other functions

if __name__ == '__main__':
    asyncio.run(main())
```

**Client:**

```
import asyncio
import ucp
from ucp import Endpoint
import numpy as np

port = 15000
host = "x.x.x.x"
arr = np.random.randn(10, 10).astype(np.float32)

async def main(ep: Endpoint):
    await ep.send(arr)

async def test():
    global host, port
    ep = await ucp.create_endpoint(host, port)
    print(ep)
    
    for _ in range(10):
        await main(ep)
        await asyncio.sleep(0.5)

if __name__ == '__main__':
    asyncio.run(test())
```

**Comment by pentschev** [comment] 2024-03-09 09:40
> I previously thought that the callback function set in server create_listener can only receive/send data and then process the data, so all my functions were written in the callback function, and make `main()` code just to keep listener alive like the example code.

This will absolutely work too, in such a case your entire message exchange code should live within the callback, and once again while the endpoint is still alive (in this case, while the callback is still alive) the connection remains active.

> Now I understand that the listener can only be used to create the ep and keep it for a long time, the rest of the functionality can be implemented in the main() function.So I modified the code, but the client could not finish create_endpoint, but kept getting stuck. where is the bug in my code? Sincerely appreciate your help！

The only problem with your code is you have `ucp.create_listener` outside of the asyncio loop, the fix is to move it to `main()`. The following will work as you intended (for a single client, for multiple clients you'll need to make sure you iterate 10 times for each client, since connections are async `for _ in range(10)` will initiate as soon as the first client connects):

```patch
--- reuse_server.py.orig        2024-03-09 01:27:14.244343000 -0800
+++ reuse_server.py     2024-03-09 01:27:55.611996000 -0800
@@ -12,18 +12,19 @@
     # wait client's ep, and append ep to list
     listener_eps.append(ep)

-listener = ucp.create_listener(listener_cb, port=15000)

 async def main():
     global listener_eps
+    listener = ucp.create_listener(listener_cb, port=15000)
     while len(listener_eps) == 0:
         print(listener_eps)
         await asyncio.sleep(0.1)

     # use exist ep to recv data, do not use close() to destory ep
     # I have 4 client connect to server, so I use for loop to recv
-    for ep in listener_eps:
-        await ep.recv(buffer)
+    for _ in range(10):
+        for ep in listener_eps:
+            await ep.recv(buffer)

     # other functions

```

The equivalent "traditional" code, where endpoints don't outlive the listener's callback could look something like this:

```python
import ucp
import asyncio
import numpy as np
from ucp import Endpoint
from typing import List

buffer = np.random.randn(10, 10).astype(np.float32)
client_count = 0

async def listener_cb(ep: Endpoint):
    for _ in range(10):
        await ep.recv(buffer)

    await ep.close()
    global client_count
    client_count += 1

async def main():
    global listener
    listener = ucp.create_listener(listener_cb, port=15000)

    while not client_count == 3:
        await asyncio.sleep(0)
    listener.close()

if __name__ == '__main__':
    asyncio.run(main())
```

In the code above the server will process 3 client connections (`while not client_count == 3`), and once the last client terminates then the server closes. Notice how all message passing happens in `listener_cb` but the endpoint only closes after all messages are received, meaning the `for _ in range(10):` is the scope of your actual message passing, just like the previous case where the endpoints process messages in the scope of `main()`.

Hope this helps.

**Comment by sunkenQ** [comment] 2024-03-09 18:01
> The only problem with your code is you have `ucp.create_listener` outside of the asyncio loop, the fix is to move it to `main()`. The following will work as you intended (for a single client, for multiple clients you'll need to make sure you iterate 10 times for each client, since connections are async `for _ in range(10)` will initiate as soon as the first client connects):

Oh, I understand your code completely, it helps me a lot! But I still have a question, if I need to build a long connection on the client side, and I can't tell how many times the client is likely to send data, how should the server implement the callback function? My idea is to set an identifier in the buffer to determine if it is the last request, otherwise keep waiting for data to be received using while True. Is there a better way to do it?

Server code:
```
import ucp
import asyncio
import numpy as np
from ucp import Endpoint
from typing import List

buffer = np.random.randn(10, 10).astype(np.float32)
client_count = 0

async def listener_cb(ep: Endpoint):
    while True:
        await ep.recv(buffer)
        # buffer[-1][-1] == 1.0 means it's the last request
        if buffer[-1][-1] == 1.0:
            break

        #  other function

    await ep.close()
    global client_count
    client_count += 1

async def main():
    global listener
    listener = ucp.create_listener(listener_cb, port=15000)

    while not client_count == 3:
        await asyncio.sleep(0)
    listener.close()

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by pentschev** [comment] 2024-03-09 20:40
> My idea is to set an identifier in the buffer to determine if it is the last request, otherwise keep waiting for data to be received using while True. Is there a better way to do it?

That should work, a simpler way is doing nothing, just have your `await ep.recv(buffer)` and when the client disconnects it will raise a `UCXConnectionReset`, at that point you know the client finished the connection, you just won't know whether it completed successfully or some error occurred. If you need to distinguish between a normal client completion or an unexpected error then it's up to the application to develop a control message type to identify it's closing as expected or otherwise. For reference, in [Distributed the first message for each iteration packs a boolean identifying whether the client should `shutdown` (if `True`)](https://github.com/dask/distributed/blob/043876806d42880db0bf1405f16c514a19def838/distributed/comm/ucx.py#L419) or [should not `shutdown` (if `False`)](https://github.com/dask/distributed/blob/043876806d42880db0bf1405f16c514a19def838/distributed/comm/ucx.py#L316), and [the receiver will then parse the `shutdown` information accordingly](https://github.com/dask/distributed/blob/043876806d42880db0bf1405f16c514a19def838/distributed/comm/ucx.py#L351-L354).

**Comment by sunkenQ** [comment] 2024-03-10 07:32
I found this try except approach as well, and I'll do some more experiments in my project. I was pleasurable to find a communication library for ucx in the distribute repository. Thank you for your patient explanation and help, it really helped me a lot!

**Closed** 2024-03-10 09:40 UTC
