### ISSUE TITLE
Maintain Changelog

### ISSUE THREAD

**Issue by quasiben** [rapidsai/ucx-py#658] opened 2020-11-14 18:22 UTC
I think we should start a changelog for ucx-py.  I think we have some stability now between major transports (TCP, NVLink, IB) and it would be good to track what is changing.  Thoughts ?

**Comment by pentschev** [comment] 2020-11-16 09:31
> I think we should start a changelog for ucx-py. I think we have some stability now between major transports (TCP, NVLink, IB) and it would be good to track what is changing. Thoughts ?

That's probably a good idea.

**Comment by pentschev** [comment] 2021-08-13 21:54
Duplicate of #305 .

**Closed by pentschev** 2021-08-13 21:54 UTC
